[workspace]
members = [
    "subfile-exchange", 
    "subfile-service", 
]
resolver = "2"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

# [workspace.dependencies]
# tracing = "0.1.37"
