[workspace]
members = [
    "file-exchange", 
    "file-service", 
]
resolver = "2"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[profile.git-test]
inherits = "dev"
debug = false

# [workspace.dependencies]
# tracing = "0.1.37"
