[workspace]
members = [
    "torrent_leecher",
    "subfile-cli", 
    "torrent_helper"
]
resolver = "1"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

# [workspace.dependencies]
# tracing = "0.1.37"
