FROM rust:1.74-bookworm as build
WORKDIR /root
COPY . .
ENV SQLX_OFFLINE=true
RUN cargo build --release --bin file-service

########################################################################################
FROM debian:bookworm-slim
RUN apt-get update \
    && apt-get install -y --no-install-recommends openssl ca-certificates \
    && rm -rf /var/lib/apt/lists/*
COPY --from=build /root/target/release/file-service /usr/local/bin/
ENTRYPOINT ["/usr/local/bin/file-service"]
