FROM rust:1.74-bookworm as build
WORKDIR /root
COPY . .
RUN cargo build --release --bin file-exchange

########################################################################################

FROM debian:bookworm-slim
RUN apt-get update && apt-get install -y --no-install-recommends openssl ca-certificates \
    && rm -rf /var/lib/apt/lists/*
COPY --from=build /root/target/release/file-exchange /usr/local/bin/
ENTRYPOINT ["/usr/local/bin/file-exchange"]
