name: tests

on:
  push:
    branches: [ main, dev ]
  pull_request:
  workflow_dispatch:

jobs:
  fmt:
    name: cargo fmt
    runs-on: ubuntu-latest
    container: 
      image: rust:1.74-bookworm
    steps:
      - uses: actions/checkout@v3
      - run: |
          rustup component add rustfmt
          cargo fmt --all -- --check

  sqlx:
    name: prepare query metadata
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_HOST_AUTH_METHOD: trust
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    container: 
      image: rust:1.74-bookworm
    env:
      DATABASE_URL: postgres://postgres@postgres:5432
      SQLX_OFFLINE: true
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-sqlx-prepare-${{ hashFiles('**/Cargo.lock') }}
      - name: Install sqlx
        run: cargo install sqlx-cli --no-default-features --features postgres
      - name: Run the test sqlx migrations
        run: cargo sqlx migrate run --source file-service/migrations
      - name: Check that the sqlx prepared query metadata is up-to-date
        run: cargo sqlx prepare --workspace --check -- --all-targets --all-features

  clippy:
    name: cargo clippy
    runs-on: ubuntu-latest
    container: 
      image: rust:1.74-bookworm
    env:
      DATABASE_URL: postgres://postgres@postgres:5432
      SQLX_OFFLINE: true
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-clippy-${{ hashFiles('**/Cargo.lock') }}
      - run: |
          rustup component add clippy
          # Temporarily allowing dead-code, while denying all other warnings
          cargo clippy --all-features --all-targets -- -A dead-code -D warnings

  test-and-coverage:
    name: cargo test and coverage
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      actions: read
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_HOST_AUTH_METHOD: trust
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    container:
      image: rust:1.74-bookworm
    env:
      DATABASE_URL: postgres://postgres@postgres:5432
      SQLX_OFFLINE: true
      LLVM_PROFILE_FILE_NAME: '{}-%Nm.profraw'
    steps:
      - name: Free some space
        run: |
          rm -rf /usr/share/dotnet
          rm -rf /opt/ghc
          rm -rf "/usr/local/share/boost"
          rm -rf "$AGENT_TOOLSDIRECTORY"
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-test-${{ hashFiles('**/Cargo.lock') }}
      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov
      - name: Install sqlx
        run: cargo install sqlx-cli --no-default-features --features postgres
      - name: Run the test sqlx migrations
        run: cargo sqlx migrate run --source file-service/migrations
      - name: Run tests and generate coverage report
        run: cargo llvm-cov test --profile "git-test" --all-features --workspace --lcov --output-path lcov.info
      - name: Test documentation code snippets
        run: cargo test --doc --all-features --workspace
      - name: Upload coverage to Coveralls
        uses: coverallsapp/github-action@v2.2.0
        with:
          file: ./lcov.info
